### ISSUE TITLE
Feature request: Starboard

### ISSUE THREAD

**Issue by Apfel** [Keke27210/homer#19]
- starboard
- image editing stuff like NotSoBot has
- More moderation stuff like ban, kick, role, nick, logging etc
- Command for getting infos for the current call
- Fix for `h:servicetel - No description given`  lol

**Comment by iDroid27** [comment]
1. Yes
2. Homer not a meme bot xd
3. Removed because annoying to manage, [Vortex](https://github.com/jagrosh/Vortex) do the job perfectly
4. Yes
5. Since it's private cmd it doesn't need... wait :aha: to be fixed

**Comment by ApfelTV** [comment]
we all abuse homer for meme quotes so its a meme bot aha

**Comment by Artuto** [comment]
1. © Endless 2018
2. >Not a meme bot
:KappaLUL:
3. Yeah I agree with iDroid
4. No opinion
5. No opinion

**Comment by ApfelTV** [comment]
@Artuto add image editing tools to endless to get more tacos

**Comment by iDroid27** [comment]
:star:board: **Planned**
Incall information: **Done** - Run `h:call` during a call to get correspondent's number
Help bug: **Fixed**

**Comment by ApfelTV** [comment]
noice
