### ISSUE TITLE
AccuWeather API

### ISSUE THREAD

**Issue by larsenv** [Keke27210/homer#31]
I recommend you use the AccuWeather API we [use for the Forecast Channel](https://github.com/RiiConnect24/File-Maker/blob/master/Channels/Forecast_Channel/forecast.py). Unlike the dataservice.accuweather.com endpoint, this one has unlimited queries and is super fast. It uses XML instead of JSON.

**Comment by Artuto** [comment]
oh man this is gonna be fun

**Comment by Keke27210** [comment]
Challenge accepted

Searching for cities: `http://samsungmobile.accu-weather.com/widget/samsungmobile/city-find.asp?location=SEARCH`
If state has format `XXX (XXX)` it is international with (`COUNTRY (STATE)`)
If state has format `XXX` it is United States with `STATE`

Getting forecast using locKey: `http://accuwxandroidv3.accu-weather.com/widget/accuwxandroidv3/weather-data.asp?locationkey=KEY&language=LANG`

Should be easy enough

**Comment by Keke27210** [comment]
✅ + a prettier city selection when several cities were found

**Comment by larsenv** [comment]
You can use the latter URL as the API because it has more features. You can find all accu-weather.com subdomains with [Sublist3r](https://github.com/aboul3la/Sublist3r).
